<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container62wNRuF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container62wNRuF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container62wNRuF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container62wNRuF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container62wNRuF\App_KernelDevDebugContainer([
    'container.build_hash' => '62wNRuF',
    'container.build_id' => 'c07cab53',
    'container.build_time' => 1587555655,
], __DIR__.\DIRECTORY_SEPARATOR.'Container62wNRuF');
